### ISSUE TITLE
Generate Dataset

### ISSUE THREAD

**Issue by sameepv21** [sdascoli/odeformer#11]
Dear Authors,

I am interested in replicating the results of the paper. For that I wish to generate the dataset but I am unable to do so. I tried three methods listed below after installing all the packages.

1. python train.py --export_data True --num_workers 10 --max_dimension 6 --train_subsample_ratio 0.0 but am facing the following error "params.world_size = int(os.environ["SLURM_NTASKS"]) KeyError: 'SLURM_NTASKS in slurm.py". Am I missing something here?
2. In the scripts folder, I am trying to run python run.py but it creates the following error "No such file or directory: '/sb_u0621_liac_scratch/odeformer/experiments'". This is the same case if I try to independently run generate_data.py.
3. I tried to create the directory as instructed but still am facing the same error as 2.

It would be really helpful if you could guide me through generating the dataset.

Regards,
Sameep Vani

**Comment by sdascoli** [comment]
Hi! 
1. You probably don't have slurm installed on your machine. You'll have to adapt the codebase to avoid using slurm.
2. You have to change the folder in `run.py` to whichever location you want to log your experiment.
3. Try setting the directory to "." for example

**Comment by sameepv21** [comment]
Dear Authors,

It would be really helpful if you could point to the part of the code where you are reading the dataset. It seems that the data is saved as .prefix file and I was wondering as to read it.

Regards,
Sameep Vani
