### ISSUE TITLE
The program gets stuck at next(self.dataloader[task]) in trainer.py 

### ISSUE THREAD

**Issue by MathBon** [sdascoli/odeformer#12]
Hi. My environment is Windows, and num_workers is set to 0. I have set both the network parameters and batch size to be sufficiently small, but the iterator (self.dataloader) still be stuck when running train.py. I want to know the reason. Thank you.

**Comment by MathBon** [comment]
I've noticed that the 'while True' loop in environment.py doesn't stop, which leads to the stuckness. And the signal.SIGALRM used in def timeout() is not supported on Windows.

**Comment by zihanghliu** [comment]
Hi, I have faced the same issue when running the train.py script. Can you tell me how you managed to solve this issue? Thanks!

**Comment by MathBon** [comment]
> Hi, I have faced the same issue when running the train.py script. Can you tell me how you managed to solve this issue? Thanks!

It seems that the data processing time is too long and not the program is stuck, please try to reduce the size of the data

**Comment by zihanghliu** [comment]
Thanks! I’ll try to reduce the size of the data.
