### ISSUE TITLE
Add additional data

### ISSUE THREAD

**Issue by han495** [sdascoli/odeformer#13]
Dear Authors,
I think your paper is very effective for discovering the ODEs and I am very interested in replicating the results of this paper. Now, I'd like to add some extra data:

I found that it is possible to change the parameter value of "--reload_data" to add data, but I don't know the path to add, or the format of this parameter value, can you give me an example to illustrate? I would appreciate it if you could give me some help!

greeting
Han Xinjie

**Comment by MMathisLab** [comment]
maybe this is useful to check: https://github.com/sdascoli/odeformer/blob/main/ODEFormer_demo.ipynb
