### ISSUE TITLE
ODEBench non-importable; DEMO notebook therefore does not work

### ISSUE THREAD

**Issue by MMathisLab** [sdascoli/odeformer#15]
Dear @sdascoli, first thanks for this great work; we are excited to build on it. 

We noticed in testing your work that your `ODEBench` module has no init file, thus is not part of the `pypi' package, and therefore your demo notebook was not runnable "as is," for me. 

![Screen Shot 2024-08-14 at 5 30 33 PM](https://github.com/user-attachments/assets/8471e55d-d64e-47d9-a522-34ec52bd3710)

A simple fix is an `__init__.py` file, which I add in this PR: https://github.com/sdascoli/odeformer/pull/16

I can confirm it works now:

- pip from my fork:
<img width="719" alt="Screenshot 2024-08-14 at 12 09 32" src="https://github.com/user-attachments/assets/90bc5813-414e-4a87-825f-e2ced7ed16bc">

Results:

<img width="662" alt="Screenshot 2024-08-14 at 12 09 41" src="https://github.com/user-attachments/assets/53505bac-cc45-4f05-90d3-998828d1b3f3">

**Comment by sdascoli** [comment]
Thanks, just merged the PR!
Excited to hear what you’re up to 😃
