### ISSUE TITLE
No file odeformer.pt when running demo

### ISSUE THREAD

**Issue by Vurgit** [sdascoli/odeformer#9]
When running the demo it will report

FileNotFoundError: [Errno 2] No such file or directory: 'odeformer.pt'

where is this file?

**Comment by soerenab** [comment]
Hi Vurgit,

I am assuming that by demo you mean the lines from the readme page, right? I.e.

```python
import odeformer
from odeformer.model import SymbolicTransformerRegressor
dstr = SymbolicTransformerRegressor(from_pretrained=True)
model_args = {'beam_size':50, 'beam_temperature':0.1}
dstr.set_model_args(model_args)

import numpy as np
from odeformer.metrics import r2_score

times = np.linspace(0, 10, 50)
x = 2.3*np.cos(times+.5)
y = 1.2*np.sin(times+.1)
trajectory = np.stack([x, y], axis=1)

candidates = dstr.fit(times, trajectory)
dstr.print(n_predictions=1)
pred_trajectory = dstr.predict(times, trajectory[0])
print(r2_score(trajectory, pred_trajectory))
```

"odeformer.pt" is the file that contains the model weights. If you initialize the model as in the code snippet above, it should be automatically downloaded as you can see here: [https://github.com/sdascoli/odeformer/blob/main/odeformer/model/sklearn_wrapper.py#L45:L46](https://github.com/sdascoli/odeformer/blob/main/odeformer/model/sklearn_wrapper.py#L45:L46)

**Comment by Vurgit** [comment]
> Hi Vurgit,
> 
> I am assuming that by demo you mean the lines from the readme page, right? I.e.
> 
> ```python
> import odeformer
> from odeformer.model import SymbolicTransformerRegressor
> dstr = SymbolicTransformerRegressor(from_pretrained=True)
> model_args = {'beam_size':50, 'beam_temperature':0.1}
> dstr.set_model_args(model_args)
> 
> import numpy as np
> from odeformer.metrics import r2_score
> 
> times = np.linspace(0, 10, 50)
> x = 2.3*np.cos(times+.5)
> y = 1.2*np.sin(times+.1)
> trajectory = np.stack([x, y], axis=1)
> 
> candidates = dstr.fit(times, trajectory)
> dstr.print(n_predictions=1)
> pred_trajectory = dstr.predict(times, trajectory[0])
> print(r2_score(trajectory, pred_trajectory))
> ```
> 
> "odeformer.pt" is the file that contains the model weights. If you initialize the model as in the code snippet above, it should be automatically downloaded as you can see here: https://github.com/sdascoli/odeformer/blob/main/odeformer/model/sklearn_wrapper.py#L45:L46

Hi soerenab
Thank you for your reply. I just used pip install odeformer on Windows command. Will this correctly install the package?

**Comment by soerenab** [comment]
We have developed odeformer on Linux so I do not know whether the code will run out-of-the-box on Windows. Generally, your workflow is correct though: first install the package, then run the model as in the snippet above.
